<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>e5e7fa95-36d5-4f33-bf59-7f83da32b36e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Manifold.Api\Manifold.Api.csproj" />
      <ProjectReference Include="..\Manifold.Migrator\Manifold.Migrator.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.2" />
    </ItemGroup>

</Project>
